baseURL: https://apophenian.art/
languageCode: en-us
title: Apophenian
theme: hugo-creative-portfolio-theme

params:
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style: default
  description: Describe your website
  copyright: "&copy;2023-2025 Magic Ogilvie"
  sidebarAbout:
  - Art and poetry by Magic Ogilvie.

  formspreeid: xvonyobr
  email: ogilvie.magic@gmail.com

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  navlinks:
  - name: "Canvases"
    url: "canvases/"
    home: true

  - name: "Watercolors & sketches"
    url: "sketches/"

  - name: "Poetry"
    url: "poetry/"

  - name: "About"
    url: "about/"

  - name: "Get in touch"
    url: "contact/"

  social:
    #facebook: "full page or profile url in facebook"
    #googleplus: "full profile url in googleplus"
    email: "ogilvie.magic@gmail.com"
    #twitter: "full profile url in twitter"
    #linkedin: "full profile url in linkedin"
    #stackoverflow: "full profile url in stackoverflow"
    instagram: "https://www.instagram.com/albertandmary/"
    #github: "full profile url in github"
    #gitlab: "full profile url in gitlab"
    #youtube: "full profile url in youtube"
    #whatsapp: "wa.me service link"
